### ISSUE TITLE
Add a task with an exit code based on duplicate status for CI

### ISSUE THREAD

**Issue by Daenyth** [sbt/sbt-duplicates-finder#14]
I'd like to use this plugin in my CI pipeline, but it doesn't seem like there's an exit-code-friendly invocation I can use. I could implement it myself if `findDuplicates` was not `private`, but since it is, it would be awkward.

**Comment by pdalpra** [comment]
Indeed, it could be interesting to add and relatively easily to plug in the existing `checkDuplicates` function, via a additional setting key (something like `failOnDuplicates`).

**Comment by pdalpra** [comment]
Implemented as of #20, I'll release sbt-duplicates-finder this week.
