### ISSUE TITLE
Cannot resolve this plugin

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt-duplicates-finder#22]
I added `addSbtPlugin("com.github.sbt" % "sbt-duplicates-finder" % "1.0.0")` to `project/plugins.sbt` but couldn't resolve this plugin

https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.sbt/ doesn't list an entry for sbt-duplicates-finder

**Comment by pdalpra** [comment]
Hi ! 
Thx for reporting, I'll get in touch with the people in charge of sbt's bintray repository, to see why it's not available.

**Comment by pdalpra** [comment]
This has been fixed by sbt maintainers, the plugin is now available : http://dl.bintray.com/sbt/sbt-plugin-releases/com.github.sbt/sbt-duplicates-finder/

**Comment by anilkumarmyla** [comment]
@pdalpra thanks!
